// SPDX-License-Identifier: MIT OR Apache-2.0
pragma solidity ^0.8.24;

import {Test} from "./Std.sol";
import {ChannelRegistry, IRDecVerifier} from "../src/ChannelRegistry.sol";
import {RDecVerifier} from "../src/RDecVerifier.sol";

/// THE PROOF (Phase 2b-i). A **real** Groth16 proof for the `R_dec` decrement
/// circuit — generated locally by `circuits/build.sh` (circom -> snarkjs, with
/// the witness coming from the Rust `tessera-channel` example `rdec_vector`) —
/// is hard-coded here and verified on-chain by the committed `RDecVerifier`.
///
/// CI runs this WITHOUT circom/snarkjs installed: it only needs the committed
/// verifier + this pinned vector. If the verifier or the pinned proof ever drift,
/// the test fails.
///
/// What it asserts:
///   (1) the pinned proof verifies against the pinned public signals;
///   (2) the public signals equal the ones the RUST example derived
///       (Poseidon C_prev / C_next / fresh / nf_rate) — the cross-language match;
///   (3) the on-chain ZK digest of C_next equals the Rust `zk_state_digest`, and
///       `ecrecover` over it returns the Rust-derived USER address (so the SAME
///       single Poseidon commitment proven by the SNARK is bound by the sig);
///   (4) end-to-end: `cooperativeCloseZK` accepts the proof + sigs and settles a
///       real on-chain channel WITHOUT any cleartext balance in calldata.
contract RDecVerifierTest is Test {
    RDecVerifier verifier;
    ChannelRegistry reg;

    // ===== R_dec proof + public signals (snarkjs `generatecall`) =====
    // Generated by `circuits/build.sh`. Public signal order is the circuit's
    // `public [C_prev, C_next, fresh, nf_rate]`.
    function _a() internal pure returns (uint256[2] memory) {
        return [
            0x1c264afc9c3685f795b5ac45b756b6f3f206e8bd21486bb550249c84cfa2c4ec,
            0x0d4621e3106a43a0fc46c8452b702151c105c40b2733d77693220d2bd13b50eb
        ];
    }

    function _b() internal pure returns (uint256[2][2] memory) {
        return [
            [
                0x17062d959304bd9e84ebfd7c18b8947fa654bf0ea14a08dbf406c2a2c3a7d8e6,
                0x234c8504aad7d7c28eb836f9e78561786a84693a44457d3d260b660e50d3bc34
            ],
            [
                0x09b5183605beb161f50061ba4885c56920ed3da9763c205119029b0956dc1b82,
                0x178433350d6eda0a768d82535c23adb798e44f96fcb883d690f25dba6674d654
            ]
        ];
    }

    function _c() internal pure returns (uint256[2] memory) {
        return [
            0x148ede6e19b60e3a6ce671d66eef93704063bc21c3a085d47da1b4b84b048a2b,
            0x0cc33f4c33f485c6851ea20644293d6ca8b67048ecdfc599343b7978bb619650
        ];
    }

    function _pub() internal pure returns (uint256[4] memory) {
        return [
            0x17fe05d58665bcdf61e8734788940823143f2d9c77566f90676ef2172b6c41f7, // C_prev
            0x2ba2ed61085c8322997df388f1182cb4e733876f416e3f56b3e56eb08b300d5c, // C_next
            0x01385e5f308b7a7f86127155ab6ca591368ad633fb50d7caee5124882fc405a2, // fresh
            0x159542ad76eed46188d053889493d1e9417b42aeb5d5be658ffea1a6b4f0b019 // nf_rate
        ];
    }

    // ===== Rust-derived vector (cargo run -p tessera-channel --example rdec_vector) =====
    // The DECIMAL public signals the Rust example printed (== _pub() in hex):
    uint256 constant PUB_C_PREV =
        10852014937222910188411555234824529483097691710260592936172446281123752591863;
    uint256 constant PUB_C_NEXT =
        19737320043454124702910830189251567725779247909019542498540517390130235837788;
    uint256 constant PUB_FRESH =
        551907614674755733515201943661905562631444439500273621402483215108455794082;
    uint256 constant PUB_NF_RATE =
        9762290224755334236367648883748812583534368405355054603815349276586667978777;
    // C_next as bytes32 (the on-chain Poseidon commitment):
    bytes32 constant C_NEXT_B32 = 0x2ba2ed61085c8322997df388f1182cb4e733876f416e3f56b3e56eb08b300d5c;
    // keccak256 ZK-path signed digest Rust produced for C_next:
    bytes32 constant ZK_DIGEST = 0x07f3535be260d9f55cbded10185250b09d679ef72e9de1bd7cacbc87d06c0114;
    // The user's recoverable secp256k1 signature over ZK_DIGEST:
    address constant USER_ADDR = 0x0c8DA9808f8b12E05404267590E1840C4902103B;
    bytes32 constant USER_R = 0x091c3891369a31d41cae4c9be35b1425b2b99dc3514b846da8fc0c414ca6af5d;
    bytes32 constant USER_S = 0x13f34fddd841abf68ad4726498f9c605378db4ba4b0e743d30716f79c44ad242;
    uint8 constant USER_V = 27;
    // ====================================================================================

    // The relayer co-signs the SAME ZK digest. We sign it here with a test key via
    // the cheatcode (the relayer's identity is whatever address we set at open),
    // so the e2e close has a valid relayer co-signature without a second pinned
    // vector. (The cross-language pin that matters is the USER sig + the proof.)
    uint256 constant RELAYER_PK = 0xB0B;

    function setUp() public {
        verifier = new RDecVerifier();
        reg = new ChannelRegistry(IRDecVerifier(address(verifier)));
    }

    /// (1) The pinned proof verifies against the pinned public signals.
    function testPinnedProofVerifies() public view {
        assertTrue(verifier.verifyProof(_a(), _b(), _c(), _pub()), "R_dec proof must verify");
    }

    /// (2) The pinned hex public signals equal the Rust-derived decimal ones.
    function testPublicSignalsMatchRust() public pure {
        uint256[4] memory p = _pub();
        assertEq(p[0], PUB_C_PREV, "C_prev != Rust");
        assertEq(p[1], PUB_C_NEXT, "C_next != Rust");
        assertEq(p[2], PUB_FRESH, "fresh != Rust");
        assertEq(p[3], PUB_NF_RATE, "nf_rate != Rust");
        assertEq(bytes32(p[1]), C_NEXT_B32, "C_next bytes32 != Rust");
    }

    /// (3) The on-chain ZK digest of C_next matches the Rust `zk_state_digest`,
    ///     and ecrecover over it returns the Rust-derived USER address — i.e. the
    ///     SAME single Poseidon commitment the SNARK proves is bound by the sig.
    function testZkDigestAndSigBindPoseidonCommitment() public view {
        bytes32 d = reg.zkStateDigest(C_NEXT_B32);
        assertEq(d, ZK_DIGEST, "on-chain zkStateDigest != Rust zk_state_digest");
        assertEq(
            reg.recoverZkSigner(C_NEXT_B32, USER_R, USER_S, USER_V),
            USER_ADDR,
            "recoverZkSigner(user) != Rust user address"
        );
    }

    /// (4) End-to-end: a real channel cooperatively closes via the ZK path. The
    ///     proof + the user's (pinned, Rust) sig + the relayer's co-sig settle the
    ///     channel and move the escrow to the private re-mint target — with NO
    ///     cleartext balance anywhere in the calldata.
    function testCooperativeCloseZkSettlesWithoutCleartextBalance() public {
        bytes32 channelId = keccak256("zk-channel");
        address relayer = vm.addr(RELAYER_PK);
        address reMintTo = address(0xBEEF);
        uint256 b0 = 1000;

        // The relayer co-signs the SAME ZK digest the proof binds.
        (uint8 rv, bytes32 rr, bytes32 rs) = vm.sign(RELAYER_PK, ZK_DIGEST);

        vm.deal(address(this), b0);
        reg.open{value: b0}(channelId, USER_ADDR, relayer, block.timestamp + 1 days);

        uint256 reMintBefore = reMintTo.balance;
        reg.cooperativeCloseZK(
            channelId,
            _pub(),
            ChannelRegistry.Proof({a: _a(), b: _b(), c: _c()}),
            ChannelRegistry.RecSig({r: USER_R, s: USER_S, v: USER_V}),
            ChannelRegistry.RecSig({r: rr, s: rs, v: rv}),
            reMintTo
        );

        // Full escrow moved privately to the re-mint target; channel terminal.
        assertEq(reMintTo.balance - reMintBefore, b0, "escrow re-minted privately");
        (,,,,, ChannelRegistry.Status status,,,) = reg.channels(channelId);
        assertTrue(status == ChannelRegistry.Status.Closed, "channel must be Closed");
    }

    /// (5) A tampered public signal (wrong C_next) must make the proof fail —
    ///     guards against a verifier that accepts arbitrary inputs.
    function testTamperedPublicSignalFails() public view {
        uint256[4] memory p = _pub();
        p[1] = p[1] ^ 1; // flip a bit of C_next
        assertTrue(!verifier.verifyProof(_a(), _b(), _c(), p), "tampered proof must NOT verify");
    }
}
