//! Rust→Solidity **cross-language signature vector** generator (Phase 2c).
//!
//! This is the load-bearing proof that the Rust signing path and the on-chain
//! `ChannelRegistry` court agree byte-for-byte. It:
//!
//!   1. mints a keypair from a **fixed** secret (so the output is deterministic
//!      and can be hard-coded into a Foundry test);
//!   2. builds a **real** signed channel state `S_1` (open `B0=1000`, spend so
//!      `balance=600`, `seq=1`) and signs its chain-facing keccak digest
//!      recoverably (the exact `sig_user` the contract verifies);
//!   3. prints `(address, chan_id, balance, seq, salt, commitment, state_digest,
//!      r, s, v)` — the vector the Solidity test pins;
//!   4. asserts in-Rust that `recover_from_digest` returns the same address
//!      (a local sanity check; the *real* check is the Foundry test recovering
//!      the identical address via `ecrecover`).
//!
//! Run: `cargo run -p tessera-channel --example eth_vector`
//!
//! The printed values are mirrored in `contracts/test/CrossLanguageVector.t.sol`.

use tessera_channel::{Channel, ChannelState, KeyPair, SignedState, UserChannel, VerifyingKey};

/// Fixed user secret (an arbitrary nonzero scalar — NOT a real key; vectors only).
const USER_SECRET: [u8; 32] = [
    0x4c, 0x0b, 0x4e, 0x2f, 0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77, 0x88, 0x99, 0xaa, 0xbb, 0xcc,
    0xdd, 0xee, 0xff, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d,
];
/// Fixed relayer secret (distinct from the user's).
const RELAYER_SECRET: [u8; 32] = [
    0x9a, 0x77, 0x66, 0x55, 0x44, 0x33, 0x22, 0x11, 0xfe, 0xdc, 0xba, 0x98, 0x76, 0x54, 0x32, 0x10,
    0x0f, 0x1e, 0x2d, 0x3c, 0x4b, 0x5a, 0x69, 0x78, 0x87, 0x96, 0xa5, 0xb4, 0xc3, 0xd2, 0xe1, 0xf0,
];

const CHAN_ID: [u8; 32] = [0x11u8; 32];
const SALT: [u8; 32] = [0x22u8; 32];
const B0: u64 = 1_000;
const SPEND: u64 = 400; // ⇒ balance after spend = 600

fn hex32(b: &[u8]) -> String {
    format!("0x{}", hex::encode(b))
}

fn main() {
    let user = KeyPair::from_secret_bytes(&USER_SECRET).expect("valid user scalar");
    let relayer = KeyPair::from_secret_bytes(&RELAYER_SECRET).expect("valid relayer scalar");

    let chan = Channel::open(
        CHAN_ID,
        B0,
        SALT,
        user.verifying_key(),
        relayer.verifying_key(),
    );

    // Build S_1 via the real protocol: genesis → spend(400) → user signs it.
    let u = UserChannel::new(user.clone(), chan.clone());
    // The relayer's freshness challenge is irrelevant to the *durable* state sig
    // the contract checks, but `spend` needs one; use a stand-in epoch/nonce.
    let mut r = tessera_channel::RelayerChannel::new(relayer.clone(), chan.clone(), 1);
    let fresh = r.issue_challenge(0, b"onion-packet-0");
    let spend = u.spend(SPEND, &fresh).expect("within balance");
    let cosigned: SignedState = r
        .verify_and_cosign(&spend, &fresh)
        .expect("honest spend verifies");

    let state: ChannelState = cosigned.state;
    let commitment = state.commitment();
    let digest = state.state_digest();
    let sig_user = &cosigned.sig_user;
    let sig_relayer = cosigned.sig_relayer.as_ref().expect("relayer co-signed");

    // In-Rust sanity: recovering from (digest, sig) yields the user's address.
    let recovered = VerifyingKey::recover_from_digest(&digest, sig_user).expect("recover succeeds");
    assert_eq!(
        recovered.eth_address(),
        user.eth_address(),
        "Rust ecrecover-equivalent must return the signer's address"
    );
    assert!(
        cosigned.user_sig_valid(&user.verifying_key()),
        "user sig must verify"
    );
    assert!(
        cosigned.relayer_sig_valid(&relayer.verifying_key()),
        "relayer co-sig must verify"
    );

    let ur = sig_user.to_rsv();
    let rr = sig_relayer.to_rsv();

    println!("// ===== Tessera channel cross-language signature vector =====");
    println!("// Generated by `cargo run -p tessera-channel --example eth_vector`.");
    println!("// Paste into contracts/test/CrossLanguageVector.t.sol.");
    println!("address userAddr   = {};", hex_addr(&user.eth_address()));
    println!("address relayerAddr= {};", hex_addr(&relayer.eth_address()));
    println!("bytes32 chanId     = {};", hex32(&CHAN_ID));
    println!("uint64  balance    = {};", state.balance);
    println!("uint64  seq        = {};", state.seq);
    println!("bytes32 salt       = {};", hex32(&SALT));
    println!("uint256 b0         = {};", B0);
    println!("// SHA-256 state commitment S_i (internal):");
    println!("bytes32 commitment = {};", hex32(&commitment));
    println!("// keccak256 chain-facing signed digest (what ecrecover consumes):");
    println!("bytes32 digest     = {};", hex32(&digest));
    println!("// user signature (r,s,v):");
    println!("bytes32 userR      = {};", hex32(&ur[..32]));
    println!("bytes32 userS      = {};", hex32(&ur[32..64]));
    println!("uint8   userV      = {};", ur[64]);
    println!("// relayer co-signature (r,s,v):");
    println!("bytes32 relayerR   = {};", hex32(&rr[..32]));
    println!("bytes32 relayerS   = {};", hex32(&rr[32..64]));
    println!("uint8   relayerV   = {};", rr[64]);
    println!("// ===========================================================");
}

fn hex_addr(a: &[u8; 20]) -> String {
    format!("0x{}", hex::encode(a))
}
