#!/usr/bin/env python3
"""Normalize the snarkjs-exported Groth16 Solidity verifier for the Tessera
dependency-free Foundry project.

snarkjs emits a `Groth16Verifier` contract with a loose pragma. We:
  * pin the pragma to ^0.8.24 (the project's solc),
  * rename the contract to `RDecVerifier` (its role here),
  * keep the verifier logic byte-for-byte otherwise (it is generated from the
    proving key — do NOT hand-edit the pairing constants).

Usage: fixup_verifier.py <in.sol> <out.sol>
"""
import re
import sys


def main() -> None:
    src, dst = sys.argv[1], sys.argv[2]
    with open(src, "r", encoding="utf-8") as f:
        code = f.read()

    # Pin the pragma (snarkjs writes e.g. `pragma solidity >=0.7.0 <0.9.0;`).
    code = re.sub(r"pragma solidity[^;]*;", "pragma solidity ^0.8.24;", code, count=1)

    # Rename the contract so it reads as the R_dec verifier in our court.
    code = code.replace("contract Groth16Verifier", "contract RDecVerifier")

    header = (
        "// SPDX-License-Identifier: GPL-3.0\n"
        "// GENERATED by snarkjs `zkey export solidityverifier` then normalized by\n"
        "// circuits/fixup_verifier.py. DO NOT hand-edit the pairing constants: they\n"
        "// are derived from the R_dec proving key (circuits/R_dec.circom) under a\n"
        "// TEST-ONLY single-party dev ceremony (see circuits/README.md). Re-run\n"
        "// circuits/build.sh to regenerate this file and the pinned proof vector.\n"
    )
    # Drop the original SPDX line if present; prepend our header.
    code = re.sub(r"^//\s*SPDX-License-Identifier:[^\n]*\n", "", code, count=1)
    code = header + code

    with open(dst, "w", encoding="utf-8") as f:
        f.write(code)
    print(f"    wrote {dst}")


if __name__ == "__main__":
    main()
