// SPDX-License-Identifier: MIT OR Apache-2.0
pragma solidity ^0.8.24;

/// @notice The Groth16 verifier for the `R_dec` decrement circuit, generated by
///         `snarkjs zkey export solidityverifier` (see contracts/src/RDecVerifier.sol).
///         Public signal order matches `R_dec.circom`'s `public [..]`:
///         `[C_prev, C_next, fresh, nf_rate]`.
interface IRDecVerifier {
    function verifyProof(
        uint256[2] calldata a,
        uint256[2][2] calldata b,
        uint256[2] calldata c,
        uint256[4] calldata pubSignals
    ) external view returns (bool);
}

/// @title ChannelRegistry — the EVM on-chain court for Tessera's ZK Spilman channel
/// @notice Phase 2c of `docs/DESIGN.md` §2/§6. This is the on-chain analogue of
///         the off-chain verdict logic in `crates/tessera-channel/src/settlement.rs`:
///         it escrows the channel balance, settles cooperatively or after a
///         unilateral-close dispute window at the highest doubly-signed state,
///         slashes provable user equivocation, and refunds the user on timeout.
///
///         It verifies channel states with the EVM-native `ecrecover` precompile
///         over the SAME recoverable secp256k1 signatures that
///         `tessera-channel` (Rust) produces — see {stateDigest}. The Rust↔Solidity
///         match is pinned by `test/CrossLanguageVector.t.sol`.
///
/// @dev    UNAUDITED, testnet-only research code. Not for mainnet / real funds.
///
///         Spilman model: the escrow is spendable by *(relayer countersignature
///         on the latest state)* OR *(the user alone after `timeout`)* — the
///         refund-on-timeout branch is load-bearing for payer safety. The channel
///         is unidirectional and monotone-decrementing: `balance` is what still
///         belongs to the USER; the relayer is owed `B0 - balance`.
contract ChannelRegistry {
    // ---------------------------------------------------------------------
    // Domain separation — MUST byte-match crates/tessera-channel.
    // ---------------------------------------------------------------------

    /// SHA-256 domain for the state commitment S_i (state.rs STATE_DOMAIN).
    bytes constant STATE_DOMAIN = "tessera-channel/state/v1";
    /// keccak256 domain for the chain-facing signed digest (state.rs STATE_SIG_DOMAIN).
    bytes constant STATE_SIG_DOMAIN = "tessera-channel/state-sig/v1";
    /// keccak256 domain for the **ZK-path** signed digest (state.rs ZK_STATE_SIG_DOMAIN).
    /// Distinct from STATE_SIG_DOMAIN so a cleartext-path sig can't be replayed on
    /// the ZK path. Binds the POSEIDON commitment (not the SHA-256 one).
    bytes constant ZK_STATE_SIG_DOMAIN = "tessera-channel/zk-state-sig/v1";

    // ---------------------------------------------------------------------
    // Types
    // ---------------------------------------------------------------------

    /// A channel state `(chanId, balance, seq, salt)` — mirrors `ChannelState`.
    struct State {
        bytes32 chanId;
        uint64 balance;
        uint64 seq;
        bytes32 salt;
    }

    /// A recoverable secp256k1 signature `(r, s, v)`. Used to keep
    /// {cooperativeCloseZK}'s parameter/stack footprint small (two of these +
    /// the proof + public signals otherwise blow the EVM's 16-slot stack).
    struct RecSig {
        bytes32 r;
        bytes32 s;
        uint8 v;
    }

    /// A Groth16 proof `(a, b, c)` for `R_dec`.
    struct Proof {
        uint256[2] a;
        uint256[2][2] b;
        uint256[2] c;
    }

    enum Status {
        None, // never opened
        Open, // escrow funded, no dispute
        Disputing, // unilateral close started; challenge window open
        Closed // settled / slashed / refunded — terminal
    }

    /// Per-channel on-chain record.
    struct Channel {
        address user; // the payer; equivocation is attributed to this address
        address relayer; // the single payee / counterparty
        uint128 b0; // funded escrow B0 (== msg.value at open). Also the USER's
            // slashable stake: provable user equivocation forfeits it to the relayer.
        uint128 relayerBond; // the RELAYER's separately-funded slashable collateral.
            // 0 until the relayer calls {fundRelayerBond}. Returned to the relayer on
            // every honest close; forfeited to the user on provable relayer
            // equivocation ({slashRelayerEquivocation}). This is the on-chain teeth
            // behind DESIGN calling the relayer "bonded" — see {fundRelayerBond}.
        uint64 timeout; // refund-on-timeout deadline (unix seconds)
        Status status;
        // dispute bookkeeping (only meaningful while Disputing):
        uint64 bestSeq; // highest doubly-signed seq submitted so far
        uint64 bestBalance; // the user balance at that state
        uint64 challengeEnd; // unix second the challenge window closes
    }

    /// channelId => record.
    mapping(bytes32 => Channel) public channels;

    /// Length of the unilateral-close challenge window, in seconds.
    uint64 public constant CHALLENGE_WINDOW = 1 days;

    /// The Groth16 verifier for `R_dec` (Phase 2b-i ZK settlement path). Immutable;
    /// set once at deploy. `address(0)` disables {cooperativeCloseZK} (the cleartext
    /// court still works), which the constructor allows so the existing 2c tests —
    /// which don't need a verifier — can deploy with no argument-bearing change.
    IRDecVerifier public immutable rdecVerifier;

    // ---------------------------------------------------------------------
    // Reentrancy guard (minimal, no external dep).
    // ---------------------------------------------------------------------
    uint256 private _locked = 1;

    modifier nonReentrant() {
        require(_locked == 1, "REENTRANCY");
        _locked = 2;
        _;
        _locked = 1;
    }

    // ---------------------------------------------------------------------
    // Events
    // ---------------------------------------------------------------------
    event Opened(
        bytes32 indexed channelId, address user, address relayer, uint256 b0, uint64 timeout
    );
    event CooperativeClosed(
        bytes32 indexed channelId, uint64 seq, uint256 relayerPayout, uint256 userRefund
    );
    event DisputeStarted(bytes32 indexed channelId, uint64 seq, uint64 challengeEnd);
    event Challenged(bytes32 indexed channelId, uint64 newSeq);
    event DisputeSettled(
        bytes32 indexed channelId, uint64 seq, uint256 relayerPayout, uint256 userRefund
    );
    event Slashed(bytes32 indexed channelId, uint64 seq, uint256 toRelayer);
    /// The relayer funded (or topped up) its slashable collateral for a channel.
    event RelayerBonded(bytes32 indexed channelId, address relayer, uint256 amount, uint256 totalBond);
    /// Provable RELAYER equivocation: the relayer's bond AND the full escrow are
    /// awarded to the user (the relayer forfeits everything and is made to pay).
    event RelayerSlashed(bytes32 indexed channelId, uint64 seq, uint256 toUser);
    event RefundedOnTimeout(bytes32 indexed channelId, uint256 userRefund);
    /// A ZK cooperative close: NO cleartext balance is logged — only the opaque
    /// Poseidon settlement commitment `cNext` and the re-mint recipient. The
    /// payout split is settled PRIVATELY downstream (shielded pool re-mint), the
    /// later increment; here the full escrow moves to `reMintTo` so no balance
    /// leaks on-chain. See {cooperativeCloseZK}.
    event CooperativeClosedZK(bytes32 indexed channelId, bytes32 cNext, address reMintTo);

    // ---------------------------------------------------------------------
    // Construction
    // ---------------------------------------------------------------------

    /// @param _verifier the deployed `R_dec` Groth16 verifier, or `address(0)` to
    ///        disable the ZK settlement path (cleartext court still fully works).
    constructor(IRDecVerifier _verifier) {
        rdecVerifier = _verifier;
    }

    // ---------------------------------------------------------------------
    // Digest / verification (the cross-language crypto surface)
    // ---------------------------------------------------------------------

    /// @notice The SHA-256 state commitment S_i — byte-identical to
    ///         `ChannelState::commitment()` in Rust:
    ///         `sha256( be64(len(STATE_DOMAIN)) || STATE_DOMAIN ||
    ///                  chanId || be64(balance) || be64(seq) || salt )`.
    /// @dev    `tessera-channel` length-prefixes the domain with a big-endian
    ///         u64; `uint64(STATE_DOMAIN.length)` encodes to the same 8 BE bytes.
    function commitment(State memory s) public pure returns (bytes32) {
        return sha256(
            abi.encodePacked(
                uint64(STATE_DOMAIN.length),
                STATE_DOMAIN,
                s.chanId,
                uint64(s.balance),
                uint64(s.seq),
                s.salt
            )
        );
    }

    /// @notice The chain-facing keccak256 digest that is actually signed and fed
    ///         to `ecrecover` — byte-identical to `ChannelState::state_digest()`:
    ///         `keccak256( be64(len(STATE_SIG_DOMAIN)) || STATE_SIG_DOMAIN || commitment )`.
    function stateDigest(State memory s) public pure returns (bytes32) {
        return keccak256(
            abi.encodePacked(uint64(STATE_SIG_DOMAIN.length), STATE_SIG_DOMAIN, commitment(s))
        );
    }

    /// @notice The **ZK-path** chain-facing keccak256 digest — byte-identical to
    ///         `ChannelState::zk_state_digest()` in Rust:
    ///         `keccak256( be64(len(ZK_STATE_SIG_DOMAIN)) || ZK_STATE_SIG_DOMAIN ||
    ///                     poseidonCommitment )`.
    /// @param  cNext the 32-byte big-endian BN254 Poseidon commitment `C_next`
    ///         (the public signal from `R_dec`). This is the SINGLE commitment the
    ///         proof attests to and that this digest binds to the user's sig — so
    ///         no on-chain Poseidon recompute is needed (the SNARK did it).
    function zkStateDigest(bytes32 cNext) public pure returns (bytes32) {
        return keccak256(
            abi.encodePacked(uint64(ZK_STATE_SIG_DOMAIN.length), ZK_STATE_SIG_DOMAIN, cNext)
        );
    }

    /// @notice Recover the signer of a ZK-path close from `(r,s,v)` over
    ///         {zkStateDigest}(cNext). Enforces EIP-2 low-`s` like {recoverSigner}.
    function recoverZkSigner(bytes32 cNext, bytes32 r, bytes32 sigS, uint8 v)
        public
        pure
        returns (address)
    {
        if (uint256(sigS) > 0x7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5D576E7357A4501DDFE92F46681B20A0) {
            return address(0);
        }
        if (v != 27 && v != 28) {
            return address(0);
        }
        return ecrecover(zkStateDigest(cNext), v, r, sigS);
    }

    /// @notice Recover the signer of a state from a 65-byte-equivalent `(r,s,v)`
    ///         recoverable secp256k1 signature — exactly what Rust's
    ///         `VerifyingKey::recover_from_digest` does.
    /// @return The recovered address, or `address(0)` if recovery fails / `s` is
    ///         in the high half (malleable). We enforce low-`s` so a state has a
    ///         single canonical signature (matching Rust's normalized `s`).
    function recoverSigner(State memory s, bytes32 r, bytes32 sigS, uint8 v)
        public
        pure
        returns (address)
    {
        // Enforce EIP-2 low-`s`: secp256k1n/2.
        if (uint256(sigS) > 0x7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5D576E7357A4501DDFE92F46681B20A0) {
            return address(0);
        }
        if (v != 27 && v != 28) {
            return address(0);
        }
        return ecrecover(stateDigest(s), v, r, sigS);
    }

    // ---------------------------------------------------------------------
    // open
    // ---------------------------------------------------------------------

    /// @notice Open a channel, escrowing `B0 = msg.value`.
    /// @dev    Stores the genesis parameters, both participant keys (addresses),
    ///         and the refund-on-timeout deadline. The escrowed `B0` is also the
    ///         USER's slashable stake: provable user equivocation forfeits it to
    ///         the counterparty (see {slashEquivocation}). The RELAYER's stake is
    ///         separate and is funded after open via {fundRelayerBond} — it starts
    ///         at 0 here. A client SHOULD read `channels[id].relayerBond` and refuse
    ///         to route value through a channel whose relayer is under-bonded for
    ///         the amount it intends to spend; the court holds and adjudicates the
    ///         bond but does not (and cannot) mandate a minimum — that sizing is a
    ///         client/economic policy (see `docs/ECONOMICS.md`).
    /// @param  channelId opaque 32-byte channel id (pool-derived in the full design)
    /// @param  user      the payer address (equivocation is attributed here)
    /// @param  relayer   the single payee / counterparty
    /// @param  timeout   unix second after which the user may refund (must be future)
    function open(bytes32 channelId, address user, address relayer, uint256 timeout)
        external
        payable
    {
        require(channels[channelId].status == Status.None, "ALREADY_OPEN");
        require(user != address(0) && relayer != address(0), "ZERO_ADDR");
        require(user != relayer, "SAME_PARTY");
        require(msg.value > 0, "ZERO_ESCROW");
        require(msg.value <= type(uint128).max, "ESCROW_TOO_LARGE");
        require(timeout > block.timestamp, "TIMEOUT_IN_PAST");
        require(timeout <= type(uint64).max, "TIMEOUT_TOO_LARGE");

        channels[channelId] = Channel({
            user: user,
            relayer: relayer,
            // forge-lint: disable-next-line(unsafe-typecast)
            b0: uint128(msg.value),
            relayerBond: 0, // funded separately by the relayer via {fundRelayerBond}
            // forge-lint: disable-next-line(unsafe-typecast)
            timeout: uint64(timeout),
            status: Status.Open,
            bestSeq: 0,
            bestBalance: 0,
            challengeEnd: 0
        });

        // forge-lint: disable-next-line(unsafe-typecast)
        emit Opened(channelId, user, relayer, msg.value, uint64(timeout));
    }

    // ---------------------------------------------------------------------
    // fundRelayerBond — the relayer's slashable on-chain collateral
    // ---------------------------------------------------------------------

    /// @notice Deposit (or top up) the relayer's slashable bond for a channel.
    ///         Callable only by the channel's registered relayer, only while Open.
    /// @dev    This is the on-chain teeth behind DESIGN's "bonded relayer": the
    ///         deposit is the relayer's OWN funds, held separately from the user
    ///         escrow `b0`. It is returned to the relayer on every honest terminal
    ///         path (cooperative/dispute close, ZK close, timeout refund, and even a
    ///         user-equivocation slash — the relayer was not at fault there), and is
    ///         forfeited to the user ONLY on provable relayer equivocation
    ///         ({slashRelayerEquivocation}).
    ///
    ///         Liveness is deliberately NOT slashable: a relayer that simply goes
    ///         dark cannot be proven faulty on-chain (you cannot prove a missing
    ///         relay), so {refundOnTimeout} returns the user's escrow AND the
    ///         relayer's bond — the relayer's punishment for going dark is losing
    ///         future fees, not its collateral. Only cryptographically-provable
    ///         equivocation burns the bond.
    /// @param  channelId the channel to bond (must be Open; caller must be relayer)
    function fundRelayerBond(bytes32 channelId) external payable {
        Channel storage ch = channels[channelId];
        require(ch.status == Status.Open, "NOT_OPEN");
        require(msg.sender == ch.relayer, "NOT_RELAYER");
        require(msg.value > 0, "ZERO_BOND");
        uint256 newTotal = uint256(ch.relayerBond) + msg.value;
        require(newTotal <= type(uint128).max, "BOND_TOO_LARGE");
        // forge-lint: disable-next-line(unsafe-typecast)
        ch.relayerBond = uint128(newTotal);
        emit RelayerBonded(channelId, msg.sender, msg.value, newTotal);
    }

    // ---------------------------------------------------------------------
    // cooperativeClose
    // ---------------------------------------------------------------------

    /// @notice Cooperative close at a doubly-signed `state`: pay the relayer
    ///         `B0 - balance` and refund the user `balance` (they sum to B0).
    /// @dev    Mirrors `Verdict::Settle`. Requires BOTH a valid user signature and
    ///         a valid relayer co-signature over the state (i.e. a doubly-signed
    ///         "unit of truth"). Checks-effects-interactions + nonReentrant.
    /// @param  state         the agreed final state (`chanId` must match)
    /// @param  userR/S/V     the user's recoverable secp256k1 signature
    /// @param  relayerR/S/V  the relayer's co-signature over the same state
    function cooperativeClose(
        State calldata state,
        bytes32 userR,
        bytes32 userS,
        uint8 userV,
        bytes32 relayerR,
        bytes32 relayerS,
        uint8 relayerV
    ) external nonReentrant {
        Channel storage ch = channels[state.chanId];
        require(ch.status == Status.Open, "NOT_OPEN");
        require(state.balance <= ch.b0, "BALANCE_GT_B0");

        // Both signatures must be present and valid (doubly-signed).
        require(recoverSigner(state, userR, userS, userV) == ch.user, "BAD_USER_SIG");
        require(recoverSigner(state, relayerR, relayerS, relayerV) == ch.relayer, "BAD_RELAYER_SIG");

        uint256 relayerPayout = uint256(ch.b0) - uint256(state.balance);
        uint256 userRefund = uint256(state.balance);
        // The relayer was honest (it co-signed this close) → return its bond.
        uint256 relayerBond = uint256(ch.relayerBond);
        address user = ch.user;
        address relayer = ch.relayer;

        // Effects: terminal before any value transfer.
        ch.status = Status.Closed;

        // Interactions.
        _pay(relayer, relayerPayout + relayerBond);
        _pay(user, userRefund);

        emit CooperativeClosed(state.chanId, state.seq, relayerPayout, userRefund);
    }

    // ---------------------------------------------------------------------
    // cooperativeCloseZK — the Phase 2b-i ZERO-KNOWLEDGE settlement path
    // ---------------------------------------------------------------------

    /// @notice Cooperatively close a channel using a `R_dec` Groth16 proof,
    ///         settling **without any cleartext balance in calldata**. This is the
    ///         on-chain settlement-privacy path from DESIGN §2/§10: a close need
    ///         not doxx the user's spending to every chain observer forever.
    ///
    /// @dev    The proof's public signals are `[C_prev, C_next, fresh, nf_rate]`
    ///         (the `R_dec` order). The court:
    ///           1. verifies the Groth16 proof — i.e. that a valid monotone
    ///              decrement reaching the Poseidon commitment `C_next` exists
    ///              (range-checked balances, seq++, chan_id↔K_chan binding, etc.),
    ///              all WITHOUT revealing the balance/cost/key/salt/seq;
    ///           2. binds that SAME single Poseidon commitment `C_next` to the
    ///              user AND relayer via their recoverable secp256k1 signatures
    ///              over {zkStateDigest}(C_next) — so attribution is the out-of-band
    ///              sig (NO in-circuit ECDSA), exactly as 2c does for the cleartext
    ///              path. This is the commitment reconciliation: one Poseidon
    ///              commitment, proven in R_dec AND bound by the court's ecrecover.
    ///
    ///         HONEST LIMIT (documented, not hidden): because the balance is
    ///         hidden, the court cannot compute the user/relayer split on-chain.
    ///         So it moves the FULL escrow to a caller-supplied `reMintTo` — the
    ///         shielded-pool re-mint target — where the split is settled privately.
    ///         The shielded pool is the LATER increment (out of scope here); until
    ///         it lands, `reMintTo` is the cooperating recipient both parties agree
    ///         on off-chain. What this DOES deliver now: the channel settles and
    ///         closes with only the opaque commitment on-chain — no balance, no
    ///         cost, no trajectory. CEI + nonReentrant.
    ///
    ///         SECOND HONEST LIMIT: this path does NOT anchor `C_prev` to the
    ///         channel's genesis commitment on-chain (the cleartext `open` predates
    ///         the Poseidon commitment and stores no genesis C). The proof only
    ///         attests that `C_prev -> C_next` is a valid decrement of *some*
    ///         channel; what ties the close to THIS channel is that BOTH this
    ///         channel's registered parties co-sign `C_next`'s ZK digest — a
    ///         cooperative close, by definition both-party-agreed. A fully
    ///         unilateral ZK dispute (where one party must be forced to settle at
    ///         the latest state without the other's signature) would additionally
    ///         need the genesis C recorded at open + a public `C_prev == genesis`
    ///         (or a higher-seq override) check; that is a follow-up, not built
    ///         here. So {cooperativeCloseZK} is exactly that — *cooperative*.
    ///
    /// @param  channelId the channel to close (must be Open)
    /// @param  pubSignals `[C_prev, C_next, fresh, nf_rate]` (field elements)
    /// @param  proof     the Groth16 proof `(a, b, c)`
    /// @param  userSig   the user's sig over {zkStateDigest}(C_next)
    /// @param  relayerSig the relayer's co-sig over the same digest
    /// @param  reMintTo  the private re-mint recipient (pool note owner)
    function cooperativeCloseZK(
        bytes32 channelId,
        uint256[4] calldata pubSignals,
        Proof calldata proof,
        RecSig calldata userSig,
        RecSig calldata relayerSig,
        address reMintTo
    ) external nonReentrant {
        require(address(rdecVerifier) != address(0), "ZK_DISABLED");
        Channel storage ch = channels[channelId];
        require(ch.status == Status.Open, "NOT_OPEN");
        require(reMintTo != address(0), "ZERO_REMINT");

        // (1) The Groth16 proof must verify (a valid decrement reaching C_next).
        require(
            rdecVerifier.verifyProof(proof.a, proof.b, proof.c, pubSignals), "BAD_PROOF"
        );

        // (2) Bind the SAME Poseidon commitment C_next (pubSignals[1]) to both
        //     parties via their secp256k1 sigs over the ZK digest. No balance is
        //     revealed: cNext is an opaque field element.
        bytes32 cNext = bytes32(pubSignals[1]);
        require(
            recoverZkSigner(cNext, userSig.r, userSig.s, userSig.v) == ch.user, "BAD_USER_SIG"
        );
        require(
            recoverZkSigner(cNext, relayerSig.r, relayerSig.s, relayerSig.v) == ch.relayer,
            "BAD_RELAYER_SIG"
        );

        // The relayer co-signed this ZK close → it was honest; return its bond.
        uint256 relayerBond = uint256(ch.relayerBond);
        address relayer = ch.relayer;

        // Effects: terminal before value transfer.
        ch.status = Status.Closed;

        // Interactions: move the full escrow to the private re-mint target (the
        // split is settled privately downstream in the pool; nothing leaks
        // on-chain) and return the relayer's own bond to it directly. The bond is
        // the relayer's collateral, not part of the hidden balance, so returning
        // it on-chain reveals nothing about the user's spending.
        _pay(reMintTo, uint256(ch.b0));
        _pay(relayer, relayerBond);

        emit CooperativeClosedZK(channelId, cNext, reMintTo);
    }

    // ---------------------------------------------------------------------
    // unilateralClose + challenge + settleDispute
    // ---------------------------------------------------------------------

    /// @notice Start a unilateral close at a doubly-signed `state`, opening a
    ///         challenge window in which the counterparty can override with a
    ///         strictly-higher-seq doubly-signed state ({challenge}).
    /// @dev    Either party can start it (it requires a doubly-signed state, which
    ///         only honest cooperation could have produced). Mirrors the design's
    ///         "unilateral close opens a dispute window where the highest
    ///         doubly-signed seq wins".
    function unilateralClose(
        State calldata state,
        bytes32 userR,
        bytes32 userS,
        uint8 userV,
        bytes32 relayerR,
        bytes32 relayerS,
        uint8 relayerV
    ) external {
        Channel storage ch = channels[state.chanId];
        require(ch.status == Status.Open, "NOT_OPEN");
        require(state.balance <= ch.b0, "BALANCE_GT_B0");
        require(recoverSigner(state, userR, userS, userV) == ch.user, "BAD_USER_SIG");
        require(recoverSigner(state, relayerR, relayerS, relayerV) == ch.relayer, "BAD_RELAYER_SIG");

        ch.status = Status.Disputing;
        ch.bestSeq = state.seq;
        ch.bestBalance = state.balance;
        ch.challengeEnd = uint64(block.timestamp) + CHALLENGE_WINDOW;

        emit DisputeStarted(state.chanId, state.seq, ch.challengeEnd);
    }

    /// @notice During the challenge window, override the current best with a
    ///         STRICTLY-higher-seq doubly-signed state (the latest truth wins).
    function challenge(
        State calldata state,
        bytes32 userR,
        bytes32 userS,
        uint8 userV,
        bytes32 relayerR,
        bytes32 relayerS,
        uint8 relayerV
    ) external {
        Channel storage ch = channels[state.chanId];
        require(ch.status == Status.Disputing, "NOT_DISPUTING");
        require(block.timestamp <= ch.challengeEnd, "WINDOW_CLOSED");
        require(state.seq > ch.bestSeq, "NOT_HIGHER_SEQ");
        require(state.balance <= ch.b0, "BALANCE_GT_B0");
        require(recoverSigner(state, userR, userS, userV) == ch.user, "BAD_USER_SIG");
        require(recoverSigner(state, relayerR, relayerS, relayerV) == ch.relayer, "BAD_RELAYER_SIG");

        ch.bestSeq = state.seq;
        ch.bestBalance = state.balance;

        emit Challenged(state.chanId, state.seq);
    }

    /// @notice After the challenge window closes, settle at the highest
    ///         doubly-signed state seen: relayer gets `B0 - bestBalance`, user
    ///         gets `bestBalance`. CEI + nonReentrant.
    function settleDispute(bytes32 channelId) external nonReentrant {
        Channel storage ch = channels[channelId];
        require(ch.status == Status.Disputing, "NOT_DISPUTING");
        require(block.timestamp > ch.challengeEnd, "WINDOW_OPEN");

        uint256 relayerPayout = uint256(ch.b0) - uint256(ch.bestBalance);
        uint256 userRefund = uint256(ch.bestBalance);
        // Settling at the highest doubly-signed state is the honest dispute
        // outcome; the relayer's bond is not at stake here → return it. (Relayer
        // equivocation is punished by {slashRelayerEquivocation}, a separate path.)
        uint256 relayerBond = uint256(ch.relayerBond);
        address user = ch.user;
        address relayer = ch.relayer;
        uint64 seq = ch.bestSeq;

        ch.status = Status.Closed;

        _pay(relayer, relayerPayout + relayerBond);
        _pay(user, userRefund);

        emit DisputeSettled(channelId, seq, relayerPayout, userRefund);
    }

    // ---------------------------------------------------------------------
    // slashEquivocation
    // ---------------------------------------------------------------------

    /// @notice Slash provable user equivocation: two states at the SAME seq with
    ///         DIFFERENT commitments, both carrying the user's valid secp256k1
    ///         signature, are attributable double-spend. Mirrors
    ///         `Verdict::SlashUser`. The user's at-risk escrow/bond is forfeited
    ///         to the relayer (the bonded counterparty). CEI + nonReentrant.
    /// @dev    Only the user's signatures are required (the equivocation is the
    ///         user's fault and is provable from the user's key alone — exactly
    ///         the off-chain settlement rule: "both bear the user's valid sig").
    function slashEquivocation(
        State calldata stateA,
        State calldata stateB,
        bytes32 userRA,
        bytes32 userSA,
        uint8 userVA,
        bytes32 userRB,
        bytes32 userSB,
        uint8 userVB
    ) external nonReentrant {
        require(stateA.chanId == stateB.chanId, "DIFFERENT_CHANNEL");
        Channel storage ch = channels[stateA.chanId];
        // Slashing is valid whether the channel is Open or already Disputing.
        require(ch.status == Status.Open || ch.status == Status.Disputing, "NOT_SLASHABLE");

        require(stateA.seq == stateB.seq, "SEQ_MISMATCH");
        bytes32 cA = commitment(stateA);
        bytes32 cB = commitment(stateB);
        require(cA != cB, "SAME_COMMITMENT"); // must actually conflict

        // Both conflicting states must bear the USER's valid signature.
        require(recoverSigner(stateA, userRA, userSA, userVA) == ch.user, "BAD_USER_SIG_A");
        require(recoverSigner(stateB, userRB, userSB, userVB) == ch.user, "BAD_USER_SIG_B");

        // The user equivocated → forfeit the user's escrow to the relayer. The
        // relayer was not at fault, so its own bond is returned to it as well.
        uint256 toRelayer = uint256(ch.b0) + uint256(ch.relayerBond);
        address relayer = ch.relayer;
        uint64 seq = stateA.seq;

        ch.status = Status.Closed;

        _pay(relayer, toRelayer);

        emit Slashed(stateA.chanId, seq, toRelayer);
    }

    // ---------------------------------------------------------------------
    // slashRelayerEquivocation — the symmetric RELAYER-fault path (M1 keystone)
    // ---------------------------------------------------------------------

    /// @notice Slash provable RELAYER equivocation: two states at the SAME seq with
    ///         DIFFERENT commitments, both carrying the RELAYER's valid secp256k1
    ///         signature. An honest relayer co-signs exactly one state per seq (it
    ///         counter-signs the user's monotone decrement once), so two distinct
    ///         relayer-signed states at one seq are an attributable protocol
    ///         violation — the symmetric mirror of {slashEquivocation}.
    ///
    /// @dev    This is what makes the relayer genuinely *bonded*: the relayer
    ///         forfeits its entire on-chain stake. Because the relayer cheated, the
    ///         user is made whole on BOTH sides — it recovers the full escrow `b0`
    ///         AND is awarded the relayer's bond. (We deliberately do not try to
    ///         honour the relayer's partial earnings: under equivocation the "true"
    ///         balance is exactly what the relayer made ambiguous, so the safe,
    ///         maximally-deterrent rule is relayer-gets-nothing / user-made-whole.)
    ///
    ///         Only the relayer's signatures are needed — the fault is provable from
    ///         the relayer's key alone. A malicious user cannot fabricate this: it
    ///         cannot produce the relayer's signature, so it can only ever present
    ///         states the relayer actually signed. The signed digest folds in
    ///         `chanId` (via {commitment}), so a relayer signature from another
    ///         channel cannot be replayed here. CEI + nonReentrant.
    /// @param  stateA / stateB the two conflicting states (same chanId, same seq)
    /// @param  relayerRA/SA/VA the relayer's signature over `stateA`
    /// @param  relayerRB/SB/VB the relayer's signature over `stateB`
    function slashRelayerEquivocation(
        State calldata stateA,
        State calldata stateB,
        bytes32 relayerRA,
        bytes32 relayerSA,
        uint8 relayerVA,
        bytes32 relayerRB,
        bytes32 relayerSB,
        uint8 relayerVB
    ) external nonReentrant {
        require(stateA.chanId == stateB.chanId, "DIFFERENT_CHANNEL");
        Channel storage ch = channels[stateA.chanId];
        require(ch.status == Status.Open || ch.status == Status.Disputing, "NOT_SLASHABLE");

        require(stateA.seq == stateB.seq, "SEQ_MISMATCH");
        bytes32 cA = commitment(stateA);
        bytes32 cB = commitment(stateB);
        require(cA != cB, "SAME_COMMITMENT"); // must actually conflict

        // Both conflicting states must bear the RELAYER's valid signature.
        require(
            recoverSigner(stateA, relayerRA, relayerSA, relayerVA) == ch.relayer, "BAD_RELAYER_SIG_A"
        );
        require(
            recoverSigner(stateB, relayerRB, relayerSB, relayerVB) == ch.relayer, "BAD_RELAYER_SIG_B"
        );

        // Relayer cheated → user recovers the full escrow AND takes the bond.
        uint256 toUser = uint256(ch.b0) + uint256(ch.relayerBond);
        address user = ch.user;
        uint64 seq = stateA.seq;

        ch.status = Status.Closed;

        _pay(user, toUser);

        emit RelayerSlashed(stateA.chanId, seq, toUser);
    }

    // ---------------------------------------------------------------------
    // refundOnTimeout
    // ---------------------------------------------------------------------

    /// @notice After `timeout` with no advance (relayer-dark), refund the user
    ///         the full escrow B0. Mirrors `Verdict::RefundUser`. CEI + nonReentrant.
    /// @dev    Callable only while still `Open` (no cooperative/unilateral close
    ///         has happened). The refund branch is the payer-safety backstop.
    ///         Going dark is NOT provable equivocation, so the relayer's bond is
    ///         returned to it (not slashed) — see {fundRelayerBond}; the relayer's
    ///         penalty for unresponsiveness is lost future fees, not its collateral.
    function refundOnTimeout(bytes32 channelId) external nonReentrant {
        Channel storage ch = channels[channelId];
        require(ch.status == Status.Open, "NOT_OPEN");
        require(block.timestamp >= ch.timeout, "BEFORE_TIMEOUT");

        uint256 userRefund = uint256(ch.b0);
        uint256 relayerBond = uint256(ch.relayerBond);
        address user = ch.user;
        address relayer = ch.relayer;

        ch.status = Status.Closed;

        _pay(user, userRefund);
        _pay(relayer, relayerBond);

        emit RefundedOnTimeout(channelId, userRefund);
    }

    // ---------------------------------------------------------------------
    // internals
    // ---------------------------------------------------------------------

    /// @dev Pay `amount` to `to` (no-op on zero). Reverts on failure so a stuck
    ///      transfer cannot silently strand funds.
    function _pay(address to, uint256 amount) private {
        if (amount == 0) return;
        (bool ok,) = payable(to).call{value: amount}("");
        require(ok, "PAY_FAILED");
    }
}
